image: python
services:
  - gcr.io/diamond-privreg/lims/ipsyb-tomogram:v0.0.1
stages:
  - build
  - test

install-job:
  stage: build
  tags:
    - argus
  script:
    - pip install .[dev]

unit-test-job:
  stage: test
  tags: 
    - argus
  before_script:
    - pip install .[dev]
  script:
    - pytest tests
