image: python
services:
  - gcr.io/diamond-privreg/lims/ipsyb-tomogram:v0.0.5
stages:
  - build
  - test

install-job:
  stage: build
  tags:
    - argus
  script:
    - pip install .[dev]

integration-test-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - pytest tests -W ignore::DeprecationWarning
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
