image: python
services:
  - gcr.io/diamond-privreg/lims/ipsyb-tomogram:v0.2.4
stages:
  - test
  - build

install-job:
  stage: test
  tags:
    - argus
  script:
    - pip install .[dev]

integration-test-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - pytest tests -W ignore::DeprecationWarning
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml

build-image:
  stage: build
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  only:
    - tags
  variables:
    IMAGE_NAME: gcr.io/diamond-pubreg/pato/backend:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $IMAGE_NAME

sync-deploy-versions:
  stage: build
  tags:
    - docker-image
  image:
    name: alpine/curl
  only:
    - tags
  script:
    - curl --request POST "https://${CI_SERVER_HOST}/api/v4/projects/6068/trigger/pipeline?token=${CI_PIPELINE_TRIGGER}&ref=${CI_DEFAULT_BRANCH}"

sync-github:
  stage: build
  tags:
    - docker-image
  image:
    name: alpine/git
  only:
    - tags
  script:
    - rm -rf .git
    - git clone https://$CI_GITHUB_USER:$CI_GITHUB_TOKEN@github.com/diamondLightSource/pato-backend.git github-upstream && cd github-upstream
    - cp -r ../src/* src
    - git config --local user.name "Guilherme de Freitas"
    - git config --local user.email guilherme.de-freitas@diamond.ac.uk
    - git add .
    - git commit -m "Release $CI_COMMIT_TAG"
    - git push origin $CI_DEFAULT_BRANCH
