variables:
  IMAGE_NAME: gcr.io/diamond-pubreg/pato/backend:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA

image: python:3.12
services:
  - gcr.io/diamond-privreg/lims/ispyb-mock:v2.7.0
stages:
  - test
  - build
  - sync

install-job:
  stage: test
  tags:
    - argus
  script:
    - pip install .[dev]

lint-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - tox -e pre-commit

integration-test-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - tox -e pytest
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml

build-image:
  stage: build
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  only:
    - tags
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $IMAGE_NAME

check-for-vulns:
  stage: build
  tags:
    - argus
  image:
    name: aquasec/trivy:0.57.1
    entrypoint: [""]
  only:
    - tags
  script:
    - trivy --exit-code 1 --cache-dir /scratch/$USER/cache/trivy/ image --ignore-unfixed -s CRITICAL $IMAGE_NAME
  needs:
    - build-image

sync-deploy-versions:
  stage: sync
  tags:
    - docker-image
  image:
    name: alpine/curl
  only:
    - tags
  script:
    - curl --request POST "https://${CI_SERVER_HOST}/api/v4/projects/6068/trigger/pipeline?token=${CI_PIPELINE_TRIGGER}&ref=${CI_DEFAULT_BRANCH}"

sync-github:
  stage: sync
  tags:
    - docker-image
  image:
    name: alpine/git
  only:
    - tags
  before_script:
    - apk add rsync
  script:
    - cd .. && git clone https://$CI_GITHUB_USER:$CI_GITHUB_TOKEN@github.com/diamondLightSource/pato-backend.git github-upstream
    - cd github-upstream
    - git remote update
    - git fetch
    - rsync -r --exclude=.git --exclude=README.rst --exclude=.gitlab-ci.yml --exclude=database --exclude=nginx --exclude=.github --delete ../pato-backend/ .
    - git config --local user.name "Guilherme de Freitas"
    - git config --local user.email guilherme.de-freitas@diamond.ac.uk
    - git add .
    - git commit -m "Release $CI_COMMIT_TAG"
    - git push origin $CI_DEFAULT_BRANCH
