repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      #- id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      #- id: black
      #  name: Run black
      #  stages: [commit]
      #  language: system
      #  entry: black --check --diff
      #  exclude: src/pato/models/table.py
      #  types: [python]

      - id: ruff
        name: Run ruff
        stages: [commit]
        language: system
        entry: ruff
        exclude: src/pato/models/table.py
        types: [python]
