apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pato
  title: PATo
  description: Single particle analysis and tomograpghy visualisation tool/API
spec:
  owner: group:lims
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pato-backend
  title: PATo Backend
  description: >
    API for PATo, a SPA/tomography visualisation tool. Has endpoints for data collections, tomograms, proposals, sessions, etc.
  links:
    - url: https://ebic-pato.diamond.ac.uk/api/docs
      title: Live server API documentation
  tags:
    - python
    - ispyb
spec:
  type: service
  lifecycle: production
  owner: group:lims
  system: pato
  providesApis:
    - pato-api
  dependsOn:
    - resource:ispyb-database
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pato-api
  description: >
    API for PATo, a SPA/tomography visualisation tool. Has endpoints for data collections, tomograms, proposals, sessions, etc.
spec:
  type: openapi
  lifecycle: production
  owner: group:lims
  system: pato
  definition:
    $text: https://ebic-pato.diamond.ac.uk/api/openapi.json
