name: Integration Tests

on:
  workflow_call:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      integration-db:
        image: ghcr.io/diamondlightsource/pato-backend-db:master
        ports:
          - 3306:3306
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Linting
        run: |
          tox -e pre-commit
      - name: Test with pytest
        env:
          CONFIG_PATH: /home/runner/work/pato-backend/pato-backend/config.json
        run: |
          tox -e pytest
